# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", inline: "echo 'Acquire::CompressionTypes::Order:: \"gz\";' > /etc/apt/apt.conf.d/99compression-workaround"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/iiab/iiab-factory/master/curl-me"
end
