# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  # Fixes Vbox boot timeout failures
  config.vm.boot_timeout = 600
  # Add a bridge network interface
  config.vm.network "public_network", type: "dhcp", bridge: "eth0"
  config.vm.network "public_network", type: "dhcp", bridge: "wlan0"
  config.vm.box = "fedora/26-cloud-base"
  # BUG curl-me script requires 'lsb_release' which is not part of Fedora core
  config.vm.provision "shell", inline: "dnf -y update && dnf -y install redhat-lsb-core"
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/iiab/iiab-factory/master/curl-me"
  config.vm.provision "shell", path: "curl-me"
end
